name: taskmaster
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter: 
    sdk: flutter
  material_color_generator: ^1.1.0
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  curved_navigation_bar: ^1.0.3
  intl: ^0.19.0
  flutter_slidable: ^3.0.1
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.1.0
  gradient_borders: ^1.0.0
  flutter_spinkit: ^5.2.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/